// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Udemy_WebAPITutorial.API.Data;

#nullable disable

namespace Udemy_WebAPITutorial.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Udemy_WebAPITutorial.API.Data.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Jamaica",
                            ShortName = "JM"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Bahamas",
                            ShortName = "BS"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Greece",
                            ShortName = "GR"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Cyprus",
                            ShortName = "CY"
                        });
                });

            modelBuilder.Entity("Udemy_WebAPITutorial.API.Data.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Pelopos 5",
                            CountryId = 3,
                            Name = "Metaksourgeio Luxury Suites",
                            Rating = 4.2999999999999998
                        },
                        new
                        {
                            Id = 2,
                            Address = "Pelopos 5",
                            CountryId = 3,
                            Name = "Arcadia Magnificent Suites",
                            Rating = 2.5
                        },
                        new
                        {
                            Id = 3,
                            Address = "Pavlos Pavlou 32",
                            CountryId = 4,
                            Name = "Cypriot Supreme",
                            Rating = 4.2000000000000002
                        },
                        new
                        {
                            Id = 4,
                            Address = "Negril",
                            CountryId = 1,
                            Name = "Sandals Resort and Spa",
                            Rating = 3.8999999999999999
                        },
                        new
                        {
                            Id = 5,
                            Address = "George Town",
                            CountryId = 2,
                            Name = "Comfort Suites",
                            Rating = 4.5
                        });
                });

            modelBuilder.Entity("Udemy_WebAPITutorial.API.Data.Hotel", b =>
                {
                    b.HasOne("Udemy_WebAPITutorial.API.Data.Country", "Country")
                        .WithMany("Hotels")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Udemy_WebAPITutorial.API.Data.Country", b =>
                {
                    b.Navigation("Hotels");
                });
#pragma warning restore 612, 618
        }
    }
}
